Hr 51/registration
UkrainianItFamily/hrtools-api pull request #1
Opened 2022-07-12 18:49 UTC by vadym980

Начеб-то всi файли додав та модифiкував.

2022-07-13 06:11 UTC, UkrainianItFamily requested changes

2022-07-13 06:11 UTC, UkrainianItFamily commented on app/Http/Controllers/Api/Auth/AuthController.php
> +        $this->middleware('auth:api', ['except' => ['login', 'register']]);
міделвар має працювати в роуті

2022-07-13 06:11 UTC, UkrainianItFamily commented on app/Http/Request/Api/Auth/RegisterHttpRequest.php
> +            'phone' => 'required|string|min:2'
телефон не може бути 2 цифри

2022-07-13 06:11 UTC, UkrainianItFamily commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('lastname');
суть міграцій в тому шоб ти не додав тут поле в міграцію... а створив нову міграцію на додавання поля... це робиться тому шо, на стейджингу міграції не запускаються заново, а мають запускатися тількі нові

2022-07-13 12:38 UTC, vadym980 commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('lastname');
задля скорочення коду, тим бiльше це новий проект

2022-07-13 15:24 UTC, vadym980 commented on app/Http/Request/Api/Auth/RegisterHttpRequest.php
> +            'phone' => 'required|string|min:2'
зробив 7

2022-07-13 15:24 UTC, vadym980 commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('lastname');
додав окремо файл мiграцii

2022-07-14 07:24 UTC, UkrainianItFamily approved these changes

2022-07-14 07:24 UTC, merged