Back/feat/hr 11/hr 38/hr 61 personal profile
UkrainianItFamily/hrtools-api pull request #14
Opened 2022-08-03 14:23 UTC by AndreyOleinych

add models factories and seeder for user data

2022-08-04 06:45 UTC, yevhen-turovets-uitf requested changes

2022-08-04 06:45 UTC, yevhen-turovets-uitf commented on app/Models/User.php
> +    public function getOblast(): ?string
область - region

2022-08-04 06:45 UTC, yevhen-turovets-uitf commented on app/Models/User.php
> +    public function getRayon(): ?string
район - area

2022-08-04 06:45 UTC, yevhen-turovets-uitf commented on app/Models/User.php
> +        return $this->marital_status;
тут же в тебе звязка?

2022-08-04 06:45 UTC, yevhen-turovets-uitf commented on database/factories/PhoneFactory.php
> +            'phone' => $this->faker->phoneNumber(),
телефон правильніше перенести в сам emergency contact

2022-08-04 06:45 UTC, yevhen-turovets-uitf commented on database/migrations/2022_08_02_160213_create_emergency_contacts_table.php
> +
сюди додати телефон

2022-08-04 06:45 UTC, yevhen-turovets-uitf commented on database/migrations/2022_08_02_114947_create_relationships_table.php
> +        });
де звязка з юзером?

2022-08-04 06:45 UTC, yevhen-turovets-uitf commented on database/migrations/2022_08_02_112555_create_marital_statuses_table.php
> +            $table->string('name');
Де звязка за юзером?

2022-08-04 06:45 UTC, yevhen-turovets-uitf commented on database/factories/RelationshipFactory.php
> +            'name' => $this->faker->randomElement(['чоловік', 'дружина', 'мати', 'батько', 'брат', 'сестра', 'інше']),
він створить рандомно з цих елементів (може бути 2 мати і так далі)... такі речі не переносять в фабрику, їх статикою набивають в сідер

2022-08-04 06:45 UTC, yevhen-turovets-uitf commented on database/factories/MaritalStatusFactory.php
> +            'name' => $this->faker->randomElement(['заміжня', 'незаміжня', 'одружений', 'неодружений']),
він створить рандомно з цих елементів (може бути 2 заміжня і так далі)... такі речі не переносять в фабрику, їх статикою набивають в сідер

2022-08-04 06:45 UTC, yevhen-turovets-uitf commented on database/factories/EmergencyContactFactory.php
> +            'user_id' => User::factory(),
сюди додати телефон

2022-08-05 09:47 UTC, AndreyOleinych commented on database/migrations/2022_08_02_114947_create_relationships_table.php
> +        });
там привязка йде не до юзера, а до екстренного контакту

2022-08-05 10:19 UTC, AndreyOleinych commented on database/migrations/2022_08_02_160213_create_emergency_contacts_table.php
> +
як ід таблиці phones?

2022-08-05 12:18 UTC, yevhen-turovets-uitf requested changes

2022-08-05 12:18 UTC, yevhen-turovets-uitf commented on app/Models/User.php
> +        //        'marital_status',
коммент

2022-08-05 12:18 UTC, yevhen-turovets-uitf commented on database/seeders/DatabaseSeeder.php
>              'phone' => '123456789012',
а чого тут телефон?

2022-08-06 20:47 UTC, yevhen-turovets-uitf requested changes

2022-08-06 20:47 UTC, yevhen-turovets-uitf commented on app/Actions/Handbook/MaritalStatusAction.php
> +        $repository = $this->maritalStatusRepository;
це зайве - ти ж вже його ініціалізував

2022-08-06 20:47 UTC, yevhen-turovets-uitf commented on app/Actions/Handbook/MaritalStatusCollectionAction.php
> +        $repository = $this->maritalStatusRepository;
це зайве - ти ж вже його ініціалізував

2022-08-06 20:47 UTC, yevhen-turovets-uitf commented on app/Actions/Handbook/MaritalStatusResponse.php
> +    public function getMaritalStatusName(): ?string
хіба тут може бути null???

2022-08-06 20:47 UTC, yevhen-turovets-uitf commented on app/Actions/Handbook/RelationshipAction.php
> +        $repository = $this->relationshipRepository;
це зайве - ти ж вже його ініціалізував

2022-08-06 20:47 UTC, yevhen-turovets-uitf commented on app/Actions/Handbook/RelationshipCollectionAction.php
> +        $repository = $this->relationshipRepository;
це зайве - ти ж вже його ініціалізував

2022-08-06 20:47 UTC, yevhen-turovets-uitf commented on app/Actions/Handbook/RelationshipResponse.php
> +        return $this->relationship->name;
тут може бути null?

2022-08-06 20:47 UTC, yevhen-turovets-uitf commented on app/Http/Controllers/Api/HandbookController.php
> +        $marital_status_id,
снейккейс

2022-08-06 20:47 UTC, yevhen-turovets-uitf commented on app/Http/Controllers/Api/HandbookController.php
> +        $relationship_id,
снейккейс

2022-08-09 11:57 UTC, yevhen-turovets-uitf approved these changes

2022-08-09 12:52 UTC, yevhen-turovets-uitf approved these changes

2022-08-09 12:52 UTC, merged