Back/feat/hr 11/hr 38/hr 61 update profile data
UkrainianItFamily/hrtools-api pull request #17
Opened 2022-08-10 16:03 UTC by AndreyOleinych

update action for profile data

2022-08-11 10:46 UTC, yevhen-turovets-uitf requested changes

2022-08-11 10:46 UTC, yevhen-turovets-uitf commented on app/Notifications/MailResetPasswordNotification.php
> +        );
використовуєшь у двох файлах - додати в окрему функцію

2022-08-11 10:46 UTC, yevhen-turovets-uitf commented on app/Notifications/EmailVerificationNotification.php
> +        );
використовуєшь у двох файлах - додати в окрему функцію

2022-08-11 10:46 UTC, yevhen-turovets-uitf commented on app/Http/Presenters/UserArrayPresenter.php
> +            'post_office' => $user->getPostOffice(),
на фронті у тебе camelCase

2022-08-11 10:46 UTC, yevhen-turovets-uitf commented on app/Http/Presenters/UserArrayPresenter.php
>              'email_verified_at' => $user->getVerifiedEmail(),
на фронті у тебе camelCase

2022-08-11 10:46 UTC, yevhen-turovets-uitf commented on app/Http/Controllers/Api/ProfileController.php
> +        );
проси шоб з фронта присилали camelCase

2022-08-11 10:46 UTC, yevhen-turovets-uitf commented on app/Actions/User/UpdateProfileAction.php
> +        }
винести це в окрму функцію (екшен для додавання резюме) в якій воно буде це все робити

2022-08-11 10:46 UTC, yevhen-turovets-uitf commented on app/Actions/User/UpdateProfileAction.php
> +        }
`$resumePath = Storage::putFileAs(
                    Config::get('filesystems.resumes_dir'),
                    $request->getResume(),
                    $request->getResume()->hashName(),
                    'public'
                );
                $resume->name = $request->getResume()->hashName();
                $resume->path = Storage::url($resumePath);
                $resume = $this->resumeRepository->save($resume);`

і оце
` $resumePath = Storage::putFileAs(
                Config::get('filesystems.resumes_dir'),
                $request->getResume(),
                $request->getResume()->hashName(),
                'public'
            );
            $resume = $this->resumeRepository->create(
                [
                    'name' => $request->getResume()->hashName(),
                    'path' => Storage::url($resumePath),
                    'user_id' => $userId,
                ]
            );`

по факту два однакові участки коду - зроби якось шоб він не повторювався

2022-08-11 17:20 UTC, yevhen-turovets-uitf requested changes

2022-08-11 17:20 UTC, yevhen-turovets-uitf commented on app/Helpers/MyUrlHelper.php
> +final class MyUrlHelper
назву класа краще так зробити шоб ясно було шо за url тут обробляється

2022-08-11 17:20 UTC, yevhen-turovets-uitf commented on app/Notifications/EmailVerificationNotification.php
> +        $customUrl = MyUrlHelper::removeDoubleShash(
что такое Shash ?

2022-08-11 17:20 UTC, yevhen-turovets-uitf commented on app/Actions/Resume/AddResumeAction.php
> +        }
це все можно обїеднати в один код використовуючи метод updateOrCreate в репозіторії

```
if ($resume->name != $resumeFile->name) {
     Storage::delete($resume->path);
}

$resume = $this->repository->updateOrCreate([
                'name' => $resumeFile->hashName(),
                'path' => Storage::url($resumePath),
                'user_id' => $userId,
]);
```

якось так...

2022-08-11 17:20 UTC, yevhen-turovets-uitf commented on app/Actions/Child/UpdateChildrenAction.php
> +                    $this->repository->delete($child['id']);
в тебе id завжди равень нулю

2022-08-11 17:20 UTC, yevhen-turovets-uitf commented on app/Actions/User/UpdateProfileAction.php
> +        }
ти ж зробив на телефони екшен, нашо тут це залишилось?

2022-08-11 17:26 UTC, AndreyOleinych commented on app/Notifications/EmailVerificationNotification.php
> +        $customUrl = MyUrlHelper::removeDoubleShash(
"/"

2022-08-12 07:18 UTC, yevhen-turovets-uitf requested changes

2022-08-12 07:18 UTC, yevhen-turovets-uitf commented on app/Actions/EmergencyContact/UpdateEmergencyContactsAction.php
> +                $contact = $this->repository->getById($emergencyContact['id']);
id

2022-08-12 07:18 UTC, yevhen-turovets-uitf commented on app/Actions/Phone/UpdateContactPhonesAction.php
> +                $this->repository->delete($contactPhone['id']);
id

2022-08-12 08:54 UTC, yevhen-turovets-uitf approved these changes

2022-08-12 08:55 UTC, merged