Hr 53/authorization
UkrainianItFamily/hrtools-api pull request #3
Opened 2022-07-12 19:24 UTC by vadym980

Added new functionality Authorization, didn't test after this action, hope all will work fine!

2022-07-14 13:46 UTC, UkrainianItFamily commented on app/Actions/Auth/LoginAction.php
> +        if (!$authResult ) {
пробіл

2022-07-14 13:47 UTC, UkrainianItFamily commented on app/Http/Controllers/Api/Auth/AuthController.php
> +    }
перенести в роути

2022-07-14 13:48 UTC, UkrainianItFamily commented on app/Http/Request/Api/Auth/LoginHttpRequest.php
> +            'email' => 'required|email',
перевірка чи є такий імейл в платформі

2022-07-14 13:48 UTC, UkrainianItFamily commented on app/Http/Request/Api/Auth/RegisterHttpRequest.php
> +            'phone' => 'required|string|min:2'
мінімум телефону

2022-07-14 13:49 UTC, UkrainianItFamily commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('lastname');
в окрему міграцію

2022-07-14 18:18 UTC, vadym980 commented on app/Actions/Auth/RegisterAction.php
> +        event(new Registered($user));
код вiдправляв пошту пiдтвердження

2022-07-14 18:52 UTC, vadym980 commented
updated with recommends

2022-07-15 04:42 UTC, UkrainianItFamily requested changes

2022-07-15 04:42 UTC, UkrainianItFamily commented on database/migrations/2022_07_14_181455_add_lastname_phone_to_users_table.php
> +            //
пуста міграція

2022-07-15 04:42 UTC, UkrainianItFamily commented on app/Http/Request/Api/Auth/LoginHttpRequest.php
> +            'email' => 'sometimes|required|email',
тут перевірка на то шо цей імейл є в системі

2022-07-15 12:42 UTC, vadym980 commented on app/Http/Request/Api/Auth/LoginHttpRequest.php
> +            'email' => 'sometimes|required|email',
трiшки переплутав, як варiант exists:users, бо iнших варiантiв не знаходжу

2022-07-18 17:12 UTC, UkrainianItFamily commented on database/migrations/2022_07_14_181455_add_lastname_phone_to_users_table.php
> +            //
не розписана функція

2022-07-18 17:42 UTC, vadym980 commented on database/migrations/2022_07_14_181455_add_lastname_phone_to_users_table.php
> +            //
доопрацював

2022-07-19 06:39 UTC, UkrainianItFamily requested changes

2022-07-19 06:39 UTC, UkrainianItFamily commented on database/migrations/2022_07_13_145211_add_lastname_phone_to_users_table.php
> +            Schema::dropIfExists('users');
ти в ап додаєшь два поля, а в довн видаляєшь усю таблицю...

2022-07-19 13:36 UTC, vadym980 commented
Правки виконано

2022-07-19 19:56 UTC, UkrainianItFamily approved these changes

2022-07-19 19:57 UTC, merged