Hr 55/reset password
UkrainianItFamily/hrtools-api pull request #4
Opened 2022-07-14 19:11 UTC by vadym980

Код вiдпрацьовуе через постмен, але потрiбно поеднати з фронтом, щоб у листi була дiйсна урл адреса, щоб користувач iз фронта мав змогу ввести електронну пошту та пароль.

2022-07-15 04:51 UTC, UkrainianItFamily requested changes

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Http/Controllers/Api/Auth/AuthController.php
> +        return $action->execute($request);
чому тут повертається екшен?

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Http/Controllers/Api/Auth/AuthController.php
> +        return $action->execute($request);
чому тут повертається екшен?

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Http/Request/Api/Auth/ApplyNewPasswordHttpRequest.php
> +            'email' => 'sometimes|required|email',
перевірка одразу чи існує імейл

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Http/Request/Api/Auth/ApplyNewPasswordHttpRequest.php
> +            'password_confirmation' => ['required',Password::min(8)->mixedCase()->numbers()],
не так це працює... для пароля ти просто ставишь шо він має бути confirmed - перевіряти password_confirmation не треба

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Http/Request/Api/Auth/ResetPasswordHttpRequest.php
> +            'email' => 'sometimes|required|email',
перевірка чи існує такий імейл

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Http/Request/ApiFormRequest.php
> +        return true;
нашо тут це?

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Models/User.php
> +    public function setPasswordAttribute($password)
шо поверстає функція?

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Models/User.php
> +    public function getJWTCustomClaims()
шо поверстає функція?

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Repository/UserRepository.php
> +    public function getUserId($user)
шо поверстає функція?

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Repository/UserRepository.php
> +    public function getUserId($user)
ми тут отримуємо тільки ID користувача?

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Repository/UserRepository.php
> +    public function getUserId($user)
в чому різниця між public function getUserId($user) і  public function getById(int $id): User

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Services/ResetsPasswords.php
> +}
дуже цікаво шо цей сервіс робить, кожна функція тут потрібна? Чому це винесено в сервіс?

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Services/SendsPasswordResetEmails.php
> +}
дуже цікаво шо цей сервіс робить, кожна функція тут потрібна? Чому це винесено в сервіс?

2022-07-15 04:51 UTC, UkrainianItFamily commented on config/app.php
перенос зайвий

2022-07-15 04:51 UTC, UkrainianItFamily commented on database/migrations/2022_07_13_165928_add_lastname_phone_to_users_table.php
> +            //
не прописана функція

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Actions/Auth/ApplyNewPasswordAction.php
> +    public function execute($request)
шо функція повертає?

2022-07-15 04:51 UTC, UkrainianItFamily commented on app/Actions/Auth/ApplyNewPasswordAction.php
> +use App\Services\ResetsPasswords;
чому це винесено в сервіс?

2022-07-15 14:32 UTC, vadym980 commented on database/migrations/2022_07_13_165928_add_lastname_phone_to_users_table.php
> +            //
було прописано

2022-07-18 17:52 UTC, vadym980 commented on app/Actions/Auth/ApplyNewPasswordAction.php
> +use App\Services\ResetsPasswords;
зміна структури вирішила проблему

2022-07-18 17:55 UTC, vadym980 commented on app/Services/SendsPasswordResetEmails.php
> +}
зміна структури вирішила проблему, видалив не потрібні функціі, впорядкував код

2022-07-18 17:55 UTC, vadym980 commented on app/Http/Request/Api/Auth/ResetPasswordHttpRequest.php
> +            'email' => 'sometimes|required|email',
доопрацьовано

2022-07-18 17:56 UTC, vadym980 commented on app/Http/Request/Api/Auth/ApplyNewPasswordHttpRequest.php
> +            'password_confirmation' => ['required',Password::min(8)->mixedCase()->numbers()],
враховано, вирішено

2022-07-18 17:57 UTC, vadym980 commented on app/Http/Controllers/Api/Auth/AuthController.php
> +        return $action->execute($request);
питання вирішено зміною структури

2022-07-19 06:42 UTC, UkrainianItFamily commented on app/Http/Request/Api/Auth/ApplyNewPasswordHttpRequest.php
> +            'password' => ['required','confirmed',Password::min(8)->mixedCase()->numbers()],
чому у другому рядку массив, а у першому по іншому запис, яка між ними різниця?

2022-07-19 06:43 UTC, UkrainianItFamily commented on database/migrations/2022_07_13_165928_add_lastname_phone_to_users_table.php
> +            Schema::dropIfExists('users');
нашо видалята прі відкаті міграції усю таблицю?

2022-07-19 18:05 UTC, vadym980 commented on database/migrations/2022_07_13_165928_add_lastname_phone_to_users_table.php
> +            Schema::dropIfExists('users');
змінено

2022-07-19 20:05 UTC, vadym980 commented on app/Actions/Auth/ResetPasswordAction.php
> +    }
в новій редакції файлу вже не використовуються

2022-07-19 20:07 UTC, vadym980 commented on app/Providers/AuthServiceProvider.php
> +        });
перероблю через .env

2022-07-20 13:35 UTC, vadym980 commented on app/Actions/Auth/ResetPasswordAction.php
> +            : ['email' => __($response)];
дійсно через ріспонс краще

2022-07-24 18:29 UTC, closed without merging